[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vote = "6wszu3thku8Dypb8hzGXS9kz6XPHXzzhWiTLaQwzzR2q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
