[package]
name = "mutable_dictionary"
version = "0.1.0"
edition = "2018"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
solana-program = "1.8.2"

[lib]
name = "mutable_dictionary"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
